name: 10x-astro-starter

services:
  dev:
    image: node:22-alpine
    working_dir: /app
    command: sh -lc "npm ci && npm run dev -- --host 0.0.0.0 --port 3001"
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    # Read-only runtime; no need for volumes

volumes:
  node_modules:
